version: '3'
services:
  db-toDoList-api:
    image: postgres:12
    restart: always
    ports:
      - 5444:5432
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: toDoList-api

  redis:
    hostname: redis
    restart: always
    container_name: redis
    image: 'redis'
    ports:
      - "6379:6379"
    volumes:
      - redis_storage:/data

volumes:
  db_storage:
  redis_storage:

